<?php include "header.php"; ?>
<?php include "navigation.php"; ?>
<?php include "slide.php"; ?>
<?php include "services.php"; ?>
<?php include "testimonials.php"; ?>
<?php include "portfolio.php"; ?>
<?php include "prices.php"; ?>
<?php include "menu.php"; ?>
<?php include "contact.php"; ?>
<?php include "social.php"; ?>
<?php include "map.php"; ?>
<?php include "footer.php"; ?>