<?php include "header.php"; ?>
<?php include "navigation.php"; ?>
<?php include "slide.php"; ?>
<?php include "services.php"; ?>
<?php include "testimonials.php"; ?>
<?php include "portfolio.php"; ?>
<?php include "prices.php"; ?>
<?php include "team.php"; ?>
<?php include "skills.php"; ?>
<?php include "social.php"; ?>
<?php include "contacts.php"; ?>
<?php include "footer.php"; ?>